### ISSUE TITLE
Yaw Rate in Stabilizer Task?

### ISSUE THREAD

**Issue by Hoverbear** [bitcraze/crazyflie-firmware#52] opened 2015-06-10 16:54 UTC
Hello,
Was doing some code review and noticed this:

```c
      if (rollType == RATE)
      {
        rollRateDesired = eulerRollDesired;
      }
      if (pitchType == RATE)
      {
        pitchRateDesired = eulerPitchDesired;
      }
      if (yawType == RATE)
      {
        yawRateDesired = -eulerYawDesired;
      }
```

[Here](https://github.com/bitcraze/crazyflie-firmware/blob/crazyflie2/modules/src/stabilizer.c#L226-L237). Is the difference in the `yawRateDesired` calculation on purpose?

**Comment by tobbeanton** [comment] 2015-08-11 14:03
Well you found an old mistake. The problem is that the mapping is wrong in many places and inverting the yaw rate here will trigger a lot of changes (cfclient, android, ios, etc). This is a bit troublesome as they all have to be updated at the same time.

**Comment by ataffanel** [comment] 2015-11-16 11:46
This won't be fixed for backward compatibility reason.

**Closed** 2015-11-16 11:46 UTC
