### ISSUE TITLE
whether the TDOA2 mode supports remote Settings of the base station

### ISSUE THREAD

**Issue by cqutyoulang** [bitcraze/crazyflie-firmware#1133] opened 2022-10-09 04:21 UTC
I can do it witch the tdoa3 model, but the tdoa2 model doesn't work. But I saw the LPP data section in the tdoa2 source code.

**Comment by krichardsson** [comment] 2022-10-10 10:49
Duplicate of https://github.com/bitcraze/lps-node-firmware/issues/61
Please don't double post questions.

**Closed by krichardsson** 2022-10-10 10:49 UTC
