### ISSUE TITLE
Whether the rateDesired.roll, rateDesired.pitch, rateDesired.yaw needs to be converted to the body coordinate system before executing the attitudeControllerCorrectRatePID(sensors->gyro.x, -sensors->gyro.y, sensors->gyro.z, rateDesired.roll, rateDesired.pitch, rateDesired.yaw); ?

### ISSUE THREAD

**Issue by HelloIDTC** [bitcraze/crazyflie-firmware#1368] opened 2024-04-23 01:53 UTC
Whether the rateDesired.roll, rateDesired.pitch, rateDesired.yaw needs to be converted to the body coordinate system before executing the attitudeControllerCorrectRatePID(sensors->gyro.x, -sensors->gyro.y, sensors->gyro.z, rateDesired.roll, rateDesired.pitch, rateDesired.yaw); ?
Because the sensors->gyro.x, gyro.y, gyro.z is measured in the body coordinate system, roll, pitch, yaw euler's angular (rate) is in Earth coordinates.

**Comment by knmcguire** [comment] 2024-04-24 07:55
Duplicate of https://github.com/orgs/bitcraze/discussions/1303 so closing.

**Closed by knmcguire** 2024-04-24 07:55 UTC
Labels: duplicate
